apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    run: my-redis
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: redis-persistent-storage
      mountPath: /data/redis
  volumes:
  - name: redis-persistent-storage
    persistentVolumeClaim:
      claimName: helloweb-disk
