apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-viewer
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-view
subjects:
- kind: ServiceAccount
  name: sa-viewer
  namespace: default
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-reader
spec:
  serviceAccountName: sa-viewer
  containers:
  - name: pod-reader
    image: gcr.io/terrycho-sandbox/pod-reader:v1
    ports:
    - containerPort: 8080
