apiVersion: v1
kind: Service
metadata:
  name: hello-node-svc-headless
spec:
  clusterIP: None
  selector:
    app: hello-node
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
