kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: accept-secureshell
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels:
      app: apiserver
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: secureshell
