apiVersion: v1
kind: Service
metadata:
  name: hello-secret-literal-svc
spec:
  selector:
    app: hello-secret-literal
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
