apiVersion: v1
kind: Service
metadata:
  name: hello-deployment-svc-clusterip
spec:
  selector:
    app: hello-deployment
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
