apiVersion: v1
kind: Service
metadata:
  name: cm-file-svc-vol
spec:
  selector:
    app: cm-file-vol
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
