apiVersion: v1
kind: Service
metadata:
  name: demo-svc
spec:
  selector:
    app: demo-deployment
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
