apiVersion: v1
kind: Service
metadata:
  name: products-node-svc
spec:
  selector:
    app: products
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
      
