apiVersion: v1
kind: ReplicationController
metadata:
  name: products-rc
spec:
  replicas: 3
  selector:
    app: products
  template:
    metadata:
      name: products-pod
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: gcr.io/terrycho-sandbox/products:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
