apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nonroot-clusterrole
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - nonroot-psp
  verbs:
  - use
