apiVersion: v1
kind: ReplicationController
metadata:
  name: users-rc
spec:
  replicas: 3
  selector:
    app: users
  template:
    metadata:
      name: users-pod
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: gcr.io/terrycho-sandbox/users:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
